// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: sendto.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendTo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CID     string `protobuf:"bytes,1,opt,name=CID,proto3" json:"CID,omitempty"`
	Seq     string `protobuf:"bytes,2,opt,name=Seq,proto3" json:"Seq,omitempty"`
	Timeout int32  `protobuf:"varint,3,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	Data    []byte `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *SendTo) Reset() {
	*x = SendTo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sendto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTo) ProtoMessage() {}

func (x *SendTo) ProtoReflect() protoreflect.Message {
	mi := &file_sendto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTo.ProtoReflect.Descriptor instead.
func (*SendTo) Descriptor() ([]byte, []int) {
	return file_sendto_proto_rawDescGZIP(), []int{0}
}

func (x *SendTo) GetCID() string {
	if x != nil {
		return x.CID
	}
	return ""
}

func (x *SendTo) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

func (x *SendTo) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *SendTo) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendToReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq  string `protobuf:"bytes,1,opt,name=Seq,proto3" json:"Seq,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *SendToReply) Reset() {
	*x = SendToReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sendto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToReply) ProtoMessage() {}

func (x *SendToReply) ProtoReflect() protoreflect.Message {
	mi := &file_sendto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToReply.ProtoReflect.Descriptor instead.
func (*SendToReply) Descriptor() ([]byte, []int) {
	return file_sendto_proto_rawDescGZIP(), []int{1}
}

func (x *SendToReply) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

func (x *SendToReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_sendto_proto protoreflect.FileDescriptor

var file_sendto_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a,
	0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x43, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65,
	0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x54,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x33, 0x0a, 0x0b, 0x53, 0x65,
	0x6e, 0x64, 0x54, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x71,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x42,
	0x15, 0x5a, 0x13, 0x2e, 0x2e, 0x2f, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sendto_proto_rawDescOnce sync.Once
	file_sendto_proto_rawDescData = file_sendto_proto_rawDesc
)

func file_sendto_proto_rawDescGZIP() []byte {
	file_sendto_proto_rawDescOnce.Do(func() {
		file_sendto_proto_rawDescData = protoimpl.X.CompressGZIP(file_sendto_proto_rawDescData)
	})
	return file_sendto_proto_rawDescData
}

var file_sendto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sendto_proto_goTypes = []interface{}{
	(*SendTo)(nil),      // 0: SendTo
	(*SendToReply)(nil), // 1: SendToReply
}
var file_sendto_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sendto_proto_init() }
func file_sendto_proto_init() {
	if File_sendto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sendto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sendto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sendto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sendto_proto_goTypes,
		DependencyIndexes: file_sendto_proto_depIdxs,
		MessageInfos:      file_sendto_proto_msgTypes,
	}.Build()
	File_sendto_proto = out.File
	file_sendto_proto_rawDesc = nil
	file_sendto_proto_goTypes = nil
	file_sendto_proto_depIdxs = nil
}
